#! /usr/bin/bash
# Media are listed in media/screenshots.txt. This file is autogenerated using the following script defined in .git/hooks/pre-commit

# Generate thumbnails
for entry in "media/hide/experiments/"*.png
do
  filename=$(basename "$entry")
  name=${filename%.*}
  ext=${filename##*.}
  ts=$(stat -c %Y $entry)
  target="media/"$ts""-""$name".thumbnail.png" 
  if [ -f "$target" ]
  then
     echo "$target"
  else
     echo "$target"
     convert $entry -thumbnail 500x64 -unsharp 0x.5 $target
  fi
done

for entry in "media/hide/experiments/"*.gif
do
  filename=$(basename "$entry")
  name=${filename%.*}
  ext=${filename##*.}
  ts=$(stat -c %Y $entry)
  target="media/"$ts""-""$name".thumbnail.gif" 
  if [ -f "$target" ]
  then
     echo "$target"
  else
     echo "$target"
     convert $entry -thumbnail 500x64 -unsharp 0x.5 $target
  fi  
done


ls -r media > media/screenshots.txt
git add media/screenshots.txt
echo "CREATE SCREENSHOT LIST"

